name: linter
version: 0.1.30-alpha.1
author: Dart Team <misc@dartlang.org>
description: Style linter for Dart.
homepage: https://github.com/dart-lang/linter
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  analyzer: ^0.29.6
  args: '>=0.12.1 <0.14.0'
  cli_util: ^0.0.1
  glob: ^1.0.3
  plugin: ^0.2.0
  source_span: ^1.0.2
  yaml: ^2.1.2
dev_dependencies:
  grinder: ^0.8.0
  markdown: ^0.11.0
  matcher: ^0.12.0
  mockito: ^1.0.0
  test: ^0.12.0
